---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-myapp
  namespace: flux-system
spec:
  chart:
    spec:
      chart: redis
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: redis
  interval: 1m0s
